[build]
  publish = "dist"
  command = "npm ci --include=dev && npm run build"

[functions]
  directory = "../functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true