[build]
  base = "Client"
  publish = "dist"
  command = "npm ci --include=dev && npm run build && cd ../server && npm ci"

[functions]
  directory = "../server/netlify/functions"
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200